import { Router } from "express";

import authRoutes from "./auth.routes";
import cashVerificationRoutes from "../modules/cash-verification/cashVerification.routes";
import companyRoutes from "../modules/company/company.routes";
import dashboardRoutes from "../modules/dashboard/dashboard.routes";
import customersRoutes from "../modules/customers/customers.routes";
import expensesRoutes from "../modules/expenses/expenses.routes";
import gstRoutes from "../modules/gst/gst.routes";
import inventoryRoutes from "../modules/inventory/inventory.routes";
import notificationsRoutes from "../modules/notifications/notifications.routes";
import accountingRoutes from "../modules/accounting/accounting.routes";
import paymentsRoutes from "../modules/payments/payments.routes";
import payrollRoutes from "../modules/payroll/payroll.routes";
import productsRoutes from "../modules/products/products.routes";
import profileRoutes from "./profile.routes";
import purchasesRoutes from "../modules/purchases/purchases.routes";
import reportsRoutes from "../modules/reports/reports.routes";
import suppliersRoutes from "../modules/suppliers/suppliers.routes";
import salesRoutes from "../modules/sales/sales.routes";
import securityAdminAuditRoutes from "../modules/security-admin/audit.routes";
import securityAdminBackupRoutes from "../modules/security-admin/backup.routes";
import settingsRoutes from "../modules/settings/settings.routes";
import siteAuditRoutes from "../modules/site-audit/siteAudit.routes";
import stockCheckRoutes from "../modules/stock-check/stockCheck.routes";
import usersRoutes from "./users.routes";

const router = Router();

router.use("/auth", authRoutes);
router.use("/accounting", accountingRoutes);
router.use("/cash-verification", cashVerificationRoutes);
router.use("/company", companyRoutes);
router.use("/dashboard", dashboardRoutes);
router.use("/customers", customersRoutes);
router.use("/expenses", expensesRoutes);
router.use("/gst", gstRoutes);
router.use("/inventory", inventoryRoutes);
router.use("/notifications", notificationsRoutes);
router.use("/payments", paymentsRoutes);
router.use("/payroll", payrollRoutes);
router.use("/purchases", purchasesRoutes);
router.use("/products", productsRoutes);
router.use("/reports", reportsRoutes);
router.use("/sales", salesRoutes);
router.use("/security-admin", securityAdminAuditRoutes);
router.use("/security-admin", securityAdminBackupRoutes);
router.use("/settings", settingsRoutes);
router.use("/site-audits", siteAuditRoutes);
router.use("/stock-check", stockCheckRoutes);
router.use("/suppliers", suppliersRoutes);
router.use("/users", usersRoutes);
router.use("/profile", profileRoutes);

export default router;
