import type { PermissionKey, Role } from "../types/auth";

export const ALL_PERMISSIONS: PermissionKey[] = [
  "customer.view",
  "customer.create",
  "customer.update",
  "customer.delete",
  "customer.ledger.view",
  "customer.export",
  "supplier.view",
  "supplier.create",
  "supplier.update",
  "supplier.delete",
  "supplier.ledger.view",
  "supplier.export",
  "product.view",
  "product.create",
  "product.update",
  "product.delete",
  "product.export",
  "product.price.view",
  "product.price.manage",
  "category.manage",
  "unit.manage",
  "inventory.view",
  "inventory.manage",
  "inventory.adjust",
  "inventory.export",
  "inventory.valuation.view",
  "warehouse.manage",
  "batch.view",
  "batch.manage",
  "purchase.view",
  "purchase.create",
  "purchase.update",
  "purchase.delete",
  "purchase.return",
  "purchase.export",
  "purchase.payment.view",
  "purchase.payment.manage",
  "purchase.approve",
  "sales.view",
  "sales.create",
  "sales.update",
  "sales.delete",
  "sales.return",
  "sales.export",
  "sales.payment.view",
  "sales.payment.manage",
  "sales.invoice.send",
  "sales.pos.access",
  "payment.view",
  "payment.receive",
  "payment.pay",
  "payment.update",
  "payment.cancel",
  "payment.export",
  "payment.receipt.print",
  "payment.reminder.manage",
  "expense.view",
  "expense.manage",
  "expense.create",
  "expense.update",
  "expense.delete",
  "expense.post",
  "expense.export",
  "expense.category.manage",
  "expense.recurring.manage",
  "accounting.view",
  "accounting.manage",
  "accounting.journal.create",
  "accounting.journal.post",
  "accounting.journal.cancel",
  "accounting.reports.view",
  "accounting.export",
  "chart.manage",
  "ledger.view",
  "cashbook.view",
  "bankbook.view",
  "gst.view",
  "gst.manage",
  "gst.export",
  "gst.itc.manage",
  "gst.adjustment.manage",
  "payroll.view",
  "payroll.employee.manage",
  "payroll.structure.manage",
  "payroll.generate",
  "payroll.pay",
  "payroll.export",
  "payroll.slip.print",
  "payroll.manage",
  "report.view",
  "report.export",
  "reports.view",
  "reports.export",
  "reports.sales.view",
  "reports.purchase.view",
  "reports.customer.view",
  "reports.supplier.view",
  "reports.inventory.view",
  "reports.expense.view",
  "reports.income.view",
  "reports.payroll.view",
  "reports.gst.view",
  "reports.accounting.view",
  "user.view",
  "user.manage",
  "settings.manage",
  "audit.view",
  "backup.manage",
];

export const PERMISSION_GROUPS: Array<{ label: string; permissions: PermissionKey[] }> = [
  {
    label: "Customer",
    permissions: ["customer.view", "customer.create", "customer.update", "customer.delete", "customer.ledger.view", "customer.export"],
  },
  {
    label: "Supplier",
    permissions: ["supplier.view", "supplier.create", "supplier.update", "supplier.delete", "supplier.ledger.view", "supplier.export"],
  },
  {
    label: "Product",
    permissions: [
      "product.view",
      "product.create",
      "product.update",
      "product.delete",
      "product.export",
      "product.price.view",
      "product.price.manage",
      "category.manage",
      "unit.manage",
    ],
  },
  {
    label: "Inventory",
    permissions: [
      "inventory.view",
      "inventory.manage",
      "inventory.adjust",
      "inventory.export",
      "inventory.valuation.view",
      "warehouse.manage",
      "batch.view",
      "batch.manage",
    ],
  },
  {
    label: "Purchase",
    permissions: [
      "purchase.view",
      "purchase.create",
      "purchase.update",
      "purchase.delete",
      "purchase.return",
      "purchase.export",
      "purchase.payment.view",
      "purchase.payment.manage",
      "purchase.approve",
    ],
  },
  {
    label: "Sales",
    permissions: [
      "sales.view",
      "sales.create",
      "sales.update",
      "sales.delete",
      "sales.return",
      "sales.export",
      "sales.payment.view",
      "sales.payment.manage",
      "sales.invoice.send",
      "sales.pos.access",
    ],
  },
  {
    label: "Payment",
    permissions: [
      "payment.view",
      "payment.receive",
      "payment.pay",
      "payment.update",
      "payment.cancel",
      "payment.export",
      "payment.receipt.print",
      "payment.reminder.manage",
    ],
  },
  {
    label: "Expense",
    permissions: [
      "expense.view",
      "expense.manage",
      "expense.create",
      "expense.update",
      "expense.delete",
      "expense.post",
      "expense.export",
      "expense.category.manage",
      "expense.recurring.manage",
    ],
  },
  {
    label: "Accounting",
    permissions: [
      "accounting.view",
      "accounting.manage",
      "accounting.journal.create",
      "accounting.journal.post",
      "accounting.journal.cancel",
      "accounting.reports.view",
      "accounting.export",
      "chart.manage",
      "ledger.view",
      "cashbook.view",
      "bankbook.view",
    ],
  },
  { label: "GST", permissions: ["gst.view", "gst.manage", "gst.export", "gst.itc.manage", "gst.adjustment.manage"] },
  {
    label: "Payroll",
    permissions: [
      "payroll.view",
      "payroll.employee.manage",
      "payroll.structure.manage",
      "payroll.generate",
      "payroll.pay",
      "payroll.export",
      "payroll.slip.print",
      "payroll.manage",
    ],
  },
  {
    label: "Reports",
    permissions: [
      "report.view",
      "report.export",
      "reports.view",
      "reports.export",
      "reports.sales.view",
      "reports.purchase.view",
      "reports.customer.view",
      "reports.supplier.view",
      "reports.inventory.view",
      "reports.expense.view",
      "reports.income.view",
      "reports.payroll.view",
      "reports.gst.view",
      "reports.accounting.view",
    ],
  },
  { label: "Users", permissions: ["user.view", "user.manage"] },
  { label: "Settings", permissions: ["settings.manage"] },
  { label: "Audit", permissions: ["audit.view"] },
  { label: "Backup", permissions: ["backup.manage"] },
];

export const DEFAULT_ROLE_PERMISSIONS: Record<Role, PermissionKey[]> = {
  admin: [...ALL_PERMISSIONS],
  accountant: [
    "customer.view",
    "customer.ledger.view",
    "customer.export",
    "supplier.view",
    "supplier.ledger.view",
    "supplier.export",
    "product.view",
    "product.export",
    "product.price.view",
    "inventory.view",
    "inventory.valuation.view",
    "inventory.export",
    "accounting.view",
    "accounting.manage",
    "accounting.journal.create",
    "accounting.journal.post",
    "accounting.journal.cancel",
    "accounting.reports.view",
    "accounting.export",
    "chart.manage",
    "ledger.view",
    "cashbook.view",
    "bankbook.view",
    "payment.view",
    "payment.receive",
    "payment.pay",
    "payment.update",
    "payment.cancel",
    "payment.export",
    "payment.receipt.print",
    "payment.reminder.manage",
    "expense.view",
    "expense.manage",
    "expense.create",
    "expense.update",
    "expense.delete",
    "expense.post",
    "expense.export",
    "expense.category.manage",
    "expense.recurring.manage",
    "gst.view",
    "gst.manage",
    "gst.export",
    "gst.itc.manage",
    "gst.adjustment.manage",
    "payroll.view",
    "payroll.employee.manage",
    "payroll.structure.manage",
    "payroll.generate",
    "payroll.pay",
    "payroll.export",
    "payroll.slip.print",
    "payroll.manage",
    "report.view",
    "report.export",
    "reports.view",
    "reports.export",
    "reports.sales.view",
    "reports.purchase.view",
    "reports.customer.view",
    "reports.supplier.view",
    "reports.inventory.view",
    "reports.expense.view",
    "reports.income.view",
    "reports.payroll.view",
    "reports.gst.view",
    "reports.accounting.view",
    "sales.view",
    "sales.export",
    "sales.payment.view",
    "sales.invoice.send",
    "purchase.view",
    "purchase.export",
    "purchase.payment.view",
    "purchase.payment.manage",
  ],
  staff: [
    "customer.view",
    "customer.create",
    "customer.update",
    "supplier.view",
    "supplier.create",
    "supplier.update",
    "product.view",
    "product.create",
    "product.update",
    "product.price.view",
    "inventory.view",
    "inventory.manage",
    "inventory.adjust",
    "purchase.view",
    "purchase.create",
    "purchase.update",
    "purchase.approve",
    "sales.view",
    "sales.create",
    "sales.update",
    "sales.return",
    "sales.pos.access",
    "expense.view",
    "expense.create",
  ],
  auditor: [
    "report.view",
    "reports.view",
    "reports.sales.view",
    "reports.purchase.view",
    "reports.customer.view",
    "reports.supplier.view",
    "reports.inventory.view",
    "reports.expense.view",
    "reports.income.view",
    "reports.payroll.view",
    "reports.gst.view",
    "reports.accounting.view",
    "audit.view",
    "accounting.view",
    "accounting.reports.view",
    "ledger.view",
    "cashbook.view",
    "bankbook.view",
    "gst.view",
    "gst.export",
    "inventory.view",
    "inventory.valuation.view",
    "purchase.view",
    "purchase.payment.view",
    "sales.view",
    "sales.payment.view",
    "expense.view",
    "payroll.view",
    "payroll.export",
  ],
};

export const ROLE_LABELS: Record<Role, string> = {
  admin: "Admin",
  accountant: "Accountant",
  staff: "Staff",
  auditor: "Auditor",
};
