import type { PermissionKey, Role } from "../types/auth";

export const ALL_PERMISSIONS: PermissionKey[] = [
  "customer.view",
  "customer.create",
  "customer.update",
  "customer.delete",
  "customer.ledger.view",
  "customer.export",
  "supplier.view",
  "supplier.create",
  "supplier.update",
  "supplier.delete",
  "supplier.ledger.view",
  "supplier.export",
  "product.view",
  "product.create",
  "product.update",
  "product.delete",
  "product.export",
  "product.price.view",
  "product.price.manage",
  "category.manage",
  "unit.manage",
  "inventory.view",
  "inventory.manage",
  "inventory.adjust",
  "inventory.export",
  "inventory.valuation.view",
  "warehouse.manage",
  "batch.view",
  "batch.manage",
  "purchase.view",
  "purchase.create",
  "purchase.update",
  "purchase.delete",
  "purchase.return",
  "purchase.export",
  "purchase.payment.view",
  "purchase.payment.manage",
  "purchase.approve",
  "sales.view",
  "sales.create",
  "sales.update",
  "sales.delete",
  "sales.return",
  "sales.export",
  "sales.payment.view",
  "sales.payment.manage",
  "sales.invoice.send",
  "sales.pos.access",
  "payment.view",
  "payment.receive",
  "payment.pay",
  "payment.update",
  "payment.cancel",
  "payment.export",
  "payment.receipt.print",
  "payment.reminder.manage",
  "expense.view",
  "expense.manage",
  "accounting.view",
  "accounting.manage",
  "gst.view",
  "gst.manage",
  "payroll.view",
  "payroll.manage",
  "report.view",
  "report.export",
  "user.view",
  "user.manage",
  "settings.manage",
  "audit.view",
  "backup.manage",
];

export const PERMISSION_GROUPS: Array<{ label: string; permissions: PermissionKey[] }> = [
  {
    label: "Customer",
    permissions: ["customer.view", "customer.create", "customer.update", "customer.delete", "customer.ledger.view", "customer.export"],
  },
  {
    label: "Supplier",
    permissions: ["supplier.view", "supplier.create", "supplier.update", "supplier.delete", "supplier.ledger.view", "supplier.export"],
  },
  {
    label: "Product",
    permissions: [
      "product.view",
      "product.create",
      "product.update",
      "product.delete",
      "product.export",
      "product.price.view",
      "product.price.manage",
      "category.manage",
      "unit.manage",
    ],
  },
  {
    label: "Inventory",
    permissions: [
      "inventory.view",
      "inventory.manage",
      "inventory.adjust",
      "inventory.export",
      "inventory.valuation.view",
      "warehouse.manage",
      "batch.view",
      "batch.manage",
    ],
  },
  {
    label: "Purchase",
    permissions: [
      "purchase.view",
      "purchase.create",
      "purchase.update",
      "purchase.delete",
      "purchase.return",
      "purchase.export",
      "purchase.payment.view",
      "purchase.payment.manage",
      "purchase.approve",
    ],
  },
  {
    label: "Sales",
    permissions: [
      "sales.view",
      "sales.create",
      "sales.update",
      "sales.delete",
      "sales.return",
      "sales.export",
      "sales.payment.view",
      "sales.payment.manage",
      "sales.invoice.send",
      "sales.pos.access",
    ],
  },
  {
    label: "Payment",
    permissions: [
      "payment.view",
      "payment.receive",
      "payment.pay",
      "payment.update",
      "payment.cancel",
      "payment.export",
      "payment.receipt.print",
      "payment.reminder.manage",
    ],
  },
  { label: "Expense", permissions: ["expense.view", "expense.manage"] },
  { label: "Accounting", permissions: ["accounting.view", "accounting.manage"] },
  { label: "GST", permissions: ["gst.view", "gst.manage"] },
  { label: "Payroll", permissions: ["payroll.view", "payroll.manage"] },
  { label: "Reports", permissions: ["report.view", "report.export"] },
  { label: "Users", permissions: ["user.view", "user.manage"] },
  { label: "Settings", permissions: ["settings.manage"] },
  { label: "Audit", permissions: ["audit.view"] },
  { label: "Backup", permissions: ["backup.manage"] },
];

export const DEFAULT_ROLE_PERMISSIONS: Record<Role, PermissionKey[]> = {
  admin: [...ALL_PERMISSIONS],
  accountant: [
    "customer.view",
    "customer.ledger.view",
    "customer.export",
    "supplier.view",
    "supplier.ledger.view",
    "supplier.export",
    "product.view",
    "product.export",
    "product.price.view",
    "inventory.view",
    "inventory.valuation.view",
    "inventory.export",
    "accounting.view",
    "accounting.manage",
    "payment.view",
    "payment.receive",
    "payment.pay",
    "payment.update",
    "payment.cancel",
    "payment.export",
    "payment.receipt.print",
    "payment.reminder.manage",
    "expense.view",
    "expense.manage",
    "gst.view",
    "gst.manage",
    "payroll.view",
    "payroll.manage",
    "report.view",
    "report.export",
    "sales.view",
    "sales.export",
    "sales.payment.view",
    "sales.invoice.send",
    "purchase.view",
    "purchase.export",
    "purchase.payment.view",
    "purchase.payment.manage",
  ],
  staff: [
    "customer.view",
    "customer.create",
    "customer.update",
    "supplier.view",
    "supplier.create",
    "supplier.update",
    "product.view",
    "product.create",
    "product.update",
    "product.price.view",
    "inventory.view",
    "inventory.manage",
    "inventory.adjust",
    "purchase.view",
    "purchase.create",
    "purchase.update",
    "purchase.approve",
    "sales.view",
    "sales.create",
    "sales.update",
    "sales.return",
    "sales.pos.access",
  ],
  auditor: [
    "report.view",
    "audit.view",
    "accounting.view",
    "gst.view",
    "inventory.view",
    "inventory.valuation.view",
    "purchase.view",
    "purchase.payment.view",
    "sales.view",
    "sales.payment.view",
  ],
};

export const ROLE_LABELS: Record<Role, string> = {
  admin: "Admin",
  accountant: "Accountant",
  staff: "Staff",
  auditor: "Auditor",
};
