export const ALL_PERMISSIONS = [
  "customer.view",
  "customer.create",
  "customer.update",
  "customer.delete",
  "customer.ledger.view",
  "customer.export",
  "supplier.view",
  "supplier.create",
  "supplier.update",
  "supplier.delete",
  "supplier.ledger.view",
  "supplier.export",
  "product.view",
  "product.create",
  "product.update",
  "product.delete",
  "product.export",
  "product.price.view",
  "product.price.manage",
  "category.manage",
  "unit.manage",
  "inventory.view",
  "inventory.manage",
  "inventory.adjust",
  "inventory.export",
  "inventory.valuation.view",
  "warehouse.manage",
  "batch.view",
  "batch.manage",
  "purchase.view",
  "purchase.create",
  "purchase.update",
  "purchase.delete",
  "purchase.return",
  "purchase.export",
  "purchase.payment.view",
  "purchase.payment.manage",
  "purchase.approve",
  "sales.view",
  "sales.create",
  "sales.update",
  "sales.delete",
  "payment.view",
  "payment.receive",
  "payment.pay",
  "expense.view",
  "expense.manage",
  "accounting.view",
  "accounting.manage",
  "gst.view",
  "gst.manage",
  "payroll.view",
  "payroll.manage",
  "report.view",
  "report.export",
  "user.view",
  "user.manage",
  "settings.manage",
  "audit.view",
  "backup.manage"
] as const;

export type PermissionKey = (typeof ALL_PERMISSIONS)[number];

const accountantPermissions: PermissionKey[] = [
  "customer.view",
  "customer.ledger.view",
  "customer.export",
  "supplier.view",
  "supplier.ledger.view",
  "supplier.export",
  "product.view",
  "product.export",
  "product.price.view",
  "inventory.view",
  "inventory.valuation.view",
  "inventory.export",
  "accounting.view",
  "accounting.manage",
  "payment.view",
  "payment.receive",
  "payment.pay",
  "expense.view",
  "expense.manage",
  "gst.view",
  "gst.manage",
  "payroll.view",
  "payroll.manage",
  "report.view",
  "report.export",
  "sales.view",
  "purchase.view",
  "purchase.export",
  "purchase.payment.view",
  "purchase.payment.manage"
];

const staffPermissions: PermissionKey[] = [
  "customer.view",
  "customer.create",
  "customer.update",
  "supplier.view",
  "supplier.create",
  "supplier.update",
  "product.view",
  "product.create",
  "product.update",
  "inventory.view",
  "inventory.manage",
  "inventory.adjust",
  "purchase.view",
  "purchase.create",
  "purchase.update",
  "purchase.approve",
  "sales.view",
  "sales.create",
  "sales.update"
];

const auditorPermissions: PermissionKey[] = [
  "customer.view",
  "customer.ledger.view",
  "supplier.view",
  "supplier.ledger.view",
  "product.view",
  "product.price.view",
  "inventory.view",
  "inventory.valuation.view",
  "report.view",
  "audit.view",
  "accounting.view",
  "gst.view",
  "purchase.view",
  "purchase.payment.view"
];

export const DEFAULT_ROLE_PERMISSIONS = {
  admin: [...ALL_PERMISSIONS],
  accountant: accountantPermissions,
  staff: staffPermissions,
  auditor: auditorPermissions
} as const;
